FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy files
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port your app uses
EXPOSE 8000

# Start the app
CMD ["uvicorn", "run:app", "--host", "0.0.0.0", "--port", "8000"]
